name: appswitcher-vue custom

# Dependency Licensing Alerts
licensing:
  conditions:
    ids:
      - GPL-*
      - LGPL-*
      - AGPL-*

  warnings:
    # Warning is the dependency isn't known
    ids:
      - Other
      - NA
  ignores:
    ids:
      - pkg:npm/escape-string-regexp@5.0.0
      - pkg:npm/path-exists@5.0.0
    names:
      - pkg:npm/slash@4.0.0
      - pkg:npm/yocto-queue@1.0.0
