// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Appswitcher: typeof import('./src/components/Appswitcher.vue')['default']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VAppBarNavIcon: typeof import('vuetify/lib')['VAppBarNavIcon']
    VAvatar: typeof import('vuetify/lib')['VAvatar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardText: typeof import('vuetify/lib')['VCardText']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VDivider: typeof import('vuetify/lib')['VDivider']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMain: typeof import('vuetify/lib')['VMain']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VNavigationDrawer: typeof import('vuetify/lib')['VNavigationDrawer']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
    VSwitch: typeof import('vuetify/lib')['VSwitch']
    VTextField: typeof import('vuetify/lib')['VTextField']
    VToolbarTitle: typeof import('vuetify/lib')['VToolbarTitle']
  }
}
